### ISSUE TITLE
define a CRD for riff system

### ISSUE THREAD

**Issue by sbawaska** [projectriff/riff#1027]
Since riff system is made up of a number of components like istio, knative, buildpacks etc and components around eventing planned, we should define a CRD which will help tying these components together. This CRD will be leveraged to install/uninstall/upgrade the riff system.

```
apiGroup: "projectriff.io/v1alpha1"
kind: Manifest
metadata:
  name: riff, riff-namespace, in-memory-channel, kafka-channel, container-source
spec:
    dependencies:
    - istio
    images:
    - projectriff/correlator:s1p2018
    - ....
    resources:
    - path: https://example.com/foo.yaml
      content: | # inlined path
      hash: deadbeef1234
      checks:
      - apiGroup: v1
        kind: Pod
        namespace: knative-serving
        name:# using a label selector instead
        labelSelector: app=controller
        jsonPath: '...'
        pattern: ;Ready=True;
    - # second resource set 
```

Once we have an object like this, we could guide the install by iterating over all resources and checking  the status of the resource before deploying the next resource. In the case of a repeat install due to a previous install failure, we can quickly do statusCheck of the resource and continue from the failure point.

Thanks @scothis for your valuable inputs in defining the structure of the CRD/object!
