### ISSUE TITLE
Explore a Function CRD

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1158]
riff 0.0.x had a first class Function CRD. With the switch to Knative, we dropped Function in favor of the Knative Service (KSvc) CRD. The distinguishing differentiator between a function and any other Knative workload is how the source was built into an image.

The riff cli was split between two distinct command groups `function` and `service`. Because function were actually services at runtime, the `function create` command actually created a KSvc resource. This created a split in commands between operations to create function `function create`, `function update`, and commands to do thing with the function at runtime like `service invoke`, `service list` and `service delete`.

We should explore shifting away from a Knative Service at the central runtime element to a Function. With a Function resource we can:
- avoid the disjoint command structures between function and service
- allow users to interact directly with function rather than requiring a CLI (most operation will likely be via a CLI/library)
- express opinions about how source is built without exposing the innards

It's most likely that Function in turn creates a Knative Service, but over time we could switch to Route and Configuration under the hood to get more control over rollouts.

Today, the riff cli creates something like:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: square-build-cache
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: square
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          annotations:
            riff.projectriff.io/build: "1"
        spec:
          serviceAccountName: riff-build
          source:
            git:
              revision: master
              url: https://github.com/projectriff-samples/node-square
          template:
            arguments:
            - name: IMAGE
              value: gcr.io/some-project/square
            - name: FUNCTION_ARTIFACT
              value: "square.js"
            - name: FUNCTION_HANDLER
              value: ""
            - name: FUNCTION_LANGUAGE
              value: ""
            - name: CACHE
              value: cache
            kind: ClusterBuildTemplate
            name: riff-cnb
          volumes:
          - name: cache
            persistentVolumeClaim:
              claimName: square-build-cache
      revisionTemplate:
        metadata:
          labels:
            riff.projectriff.io/function: upper
        spec:
          container:
            image: gcr.io/some-project/square
---
```

With a Function CRD this could look more like

```yaml
apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: square
  namespace: default
spec:
  image: gcr.io/some-project/square
  build:
    artifact: square.js
    cache: 8Gi
    source:
      git:
        revision: master
        url: https://github.com/projectriff-samples/node-square
  run:
    latest: {}
    public: true # route from outside the cluster (new)
    container: null # maybe cherry-pick fields from container instead
    volumes: null
---
```

Key benefits:
- more signal, less noise
- context that is shared between the Knative Service and Build is defined once, not twice
- we have more control over growth, like:
  - replacing Build with a CD tool
  - more advanced routing
  - protocols used to communicate with the container

Downsides:
- need a controller/webhook
  - a lot more surface area to maintain
- may end up duplicating objects with Knative unless we use Knative objects in the spec
- yet another resource for users to learn

There is much more exploratory work to be done before we make a call.
