### ISSUE TITLE
add command to faas shell script for building a Dockerfile

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#143]
this is likely to evolve (e.g. if we create a resource type for the "invokers" so that they could be referred to by a simple key), but in order to generate consistent `Dockerfile`s for a sample would require the following input:

1. invoker base
2. artifact to copy (e.g. foo.js, foo.jar, foo.sh)
3. if necessary the "handler" (e.g. classname of the Function for Java)

related to #142

**Comment by markfisher** [comment]
Whatever we call this command (using `faas generate` for this example), it could generate the YAML as well as the Dockerfile. Basically the only thing a user should need is the function code artifact, and the idea for what input and/or output topics they want to use (though later we may have an explicit "register" phase for the artifact such that it could be reusable in multiple "bindings" and even for use within composed functions).

```
./faas generate -n exclaimer -b sk8s/node-function-invoker:0.0.1 -i words -o exclamations -f exclaimer.js```

would generate:
```
`exclaimer.yaml`:
```
apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: exclaimer
spec:
  image: sk8s/exclaimer:0.0.1
  protocol: http
  input: words
  output: exclamations
```

`Dockerfile`:
```
FROM sk8s/node-function-invoker:0.0.1
ADD exclaimer.js /functions/function.js
ENV FUNCTION_URI /functions/function.js
```
