### ISSUE TITLE
Ingress service separate from HTTP gateway 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#199]
An ingress service would be useful for routing to functions which handle web requests, mapping external paths to internal.

It would also make it easier to add features like authenticated access with JWT and oAuth.

**Comment by freynca** [comment]
As a starting point, here are workloads to deploy an nginx ingress controller configuration, fronting the HTTP Gateway service:

**Default Backend**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend
```

**Ingress Controller**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.7
        name: nginx-ingress-controller
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-ing-ctl-svc
  name: nginx-ing-ctl-svc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: nginx-ingress-controller
  type: LoadBalancer
```

**Ingress Mapping**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: riff-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: <gateway.riff.example.com>    #  <-- REPLACE-ME
    http:
      paths:
      - backend:
          serviceName: <riff-http-gateway>      #  <-- REPLACE-ME
          servicePort: <riff-http-gateway-svc-port>    #  <-- REPLACE-ME
```
