### ISSUE TITLE
Function Invoker CRD

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#370]
The `riff-cli` currently compiles in support for all known function invokers that enable commands like `riff init` and `riff create`. As new function invokers are introduced, users will have a substandard experience until the cli is updated. A few cases we have already seen where the invokers and cli can drift include:
- brand new invokers (`go`)
- renamed invokers (`shell` -> `command`)
- backwards incompatible language versions (`python2` vs `python3`)
- function upgrades (`0.0.4` -> `0.0.5`)

All of this change is within our own, very small, set of invokers. We also want to encourage community invokers (ruby and kotlin have been explored), and certainly do not want to make `riff-cli` a bottleneck for new invokers.

We need a way for invokers to be discoverable by the `riff-cli`. Each invoker will provide configuration so that the cli can:
- detect which invoker to use for the given artifact by default, user should be able to override
- parameters needed for *-function.yaml (like protocol)
- scaffold the appropriate resources for the function (Dockerfile, .dockerignore, etc)

We have two simple data stores available right now: the filesystem, k8s resource configuration. A major advantage of defining the invokers in k8s is all users access the cluster will have a common set of invokers.

## CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: invokers.projectriff.io
versions:
- name: v1
spec:
  scope: Cluster
  group: projectriff.io
  version: v1
  names:
    kind: Invoker
    plural: invokers
    singular: invoker
  # todo validation
```

This proposal is for a configuration only CRD without any runtime behavior enforced by an invoker-controller. It is only used in this proposal as a central configuration that can be accessed by `riff-cli`, and has no runtime impact on the cluster.

In the future, we may want to make invokers a richer object. For example, the Function resource could default the protocol property to the protocol property of the invoker, or updating an invoker could trigger a update to all functions using that invoker. Nothing in this proposal is meant to limit a richer invoker types in the future.

## Sample Invoker

```yaml
apiVersion: projectriff.io/v1
kind: Invoker
metadata:
  name: node
spec:
  version: 0.0.5-snapshot
  matchers:
  - package.json
  - "*.js"
  properties:
    handler: # not actually used by node now, but maybe with ES Modules
      default: "<default export>"
      description: Name of exported function
    function:
      protocol: grpc
  files:
  - path: Dockerfile
    template: |
      FROM projectriff/node-function-invoker:{{.RiffVersion}}
      {{ if .FileExists("package.json") -}}
      ENV FUNCTION_URI /functions/
      COPY . ${FUNCTION_URI}
      RUN (cd ${FUNCTION_URI} && npm install --production)
      {{- else -}}
      ENV FUNCTION_URI /functions/{{.Artifact}}
      ADD {{.ArtifactBase}} ${FUNCTION_URI}
      {{- end }}
  - path: .dockerignore
    template: |
      node_modules
```

- the handler property indicate if the invoker requires a handler to be specified for the artifact
- `function` and `topics` properties represent the `spec` of the function and topics yaml files
- matchers are globs matching from the target directory or the artifact if specified. Regex may also be useful
- files are templated using the same set of properties currently used in riff-cli, plus methods that allow very basic environment testing:
  - Artifact string
  - ArtifactBase string
  - RiffVersion string
  - Handler string
  - func FileExists(string filename) bool

## CLI usage

When executing the `riff init` or `riff create` commands it should fetch the list of invokers for the cluster. For each invoker and flavor within the invoker, the matcher patterns should be checked. More specific matches (like a full file name, `package.json`) take precedence over partial matches (like a file extension, `*.js`). If there are multiple matches with the same precedence, the user should be prompted to specify the invoker.

Once a match is found, the function.yaml and topics.yaml files should be created using the respective properties merging into the `spec` section the cli currently generates. For file defined, the template should be applied to the properties and written to the file name.

When `riff update` is invoked, the current invoker version for the function should be verified against the latest invoker. If a newer version of the invoker is published, the cli can prompt to upgrade to the newer version.

**Comment by jldec** [comment]
- How would an invoker be installed in a riff system ?
- Should invoker resources include config/spec for function and topic yaml templates also ?  
  (it would be better to move ENV settings out of the Dockerfile's and into yaml configs)

**Comment by scothis** [comment]
> How would an invoker be installed in a riff system ?

`kubectl apply -f path/to/node-function-invoker.yaml`

Perhaps also

`riff apply -f path/to/node-function-invoker.yaml`

Discovery of the invoker.yaml is TBD. But worst case you could do something like:

`kubectl apply -f https://raw.githubusercontent.com/projectriff/node-function-invoker/v0.0.5/node-function-invoker.yaml`

or we could create a hosted repository:

`kubectl apply -f https://invokers.projectriff.io/node-function-invoker/v0.0.5.yaml`

> Should invoker resources include config/spec for function and topic yaml templates also ?
(it would be better to move ENV settings out of the Dockerfiles and into yaml configs)

Yes. It's a little hidden, but the sample invoker.yaml includes a bit that is meant to configure the function and topic yamls.

```yaml
...
spec:
  properties:
    function:
      protocol: grpc
```

These properties would be merged with the default that `riff-cli` provides.  So `spec/properties/function` in the invoker.yaml becomes `spec` in function.yaml. In the example, there is nothing for topics.yaml, so the default spec of `partitions: 1` would be applied.
