### ISSUE TITLE
Add --environment flag to cli init/create

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#404]
When initializing a function it would be nice to be able to pass in environment settings for the function container. We could looks for "spec.container.env" and also plain "env" in a specified yaml file.

I should be able to run `riff init --environment ./vote-counter-env.yaml` to "read" the environment from the specified file and include it in the function definition. The `vote-counter-env.yaml` file could contain:

```
    env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
```

I should be able to run `riff init --force --environment ./vote-counter-function.yaml` to "copy" the environment from the existing function definition to the new one.
