### ISSUE TITLE
kafka endpoints are inconsistent across helm and make dev-setup

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#449]
`make dev-setup` deploys kafka without helm which means that the default values for say [http-gateway kafka endpoints](https://github.com/projectriff/riff/blob/master/http-gateway/config/deployment.yaml#L30) are different from the [default values](https://github.com/projectriff/riff/blob/master/helm-charts/riff/values.yaml#L52) in the helm chart.

```yaml
env:
- name: KAFKA_BROKERS
  value: kafka.riff-system:9092
```

```yaml
kafka:
  broker:
    nodes: transport-kafka.riff-system:9092
```

This leads to unneccessary friction when developers start with say the dev setup and then switch to the helm deploy e.g. in order to test with a demo.

The ideal solution would be for helm release names NOT to leak into the dns endpoint names for kafka or any of the riff components.

If that doesn't work for some reason, it would be better for the riff dev-setup to use the same helm deploy of kafka rather than yet another different yaml deploy.
