### ISSUE TITLE
Function build with "latest" manifest seems to fail when using "--verbose" flag

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#908]
riff function build appears to fail when using `--verbose` flag - the message is:

```
Error: function creation failed: RevisionMissing: Configuration "upper" does not have any ready Revision.; Revision "upper-00001" failed with message: "The target is not receiving traffic.".
```

The function does start though, so it might be some change in the reporting of Knative build status.

**Comment by trisberg** [comment]
I've also seen this error build square node app:

```
Error: function creation failed: RevisionMissing: Configuration "square" does not have any ready Revision.; Revision "square-00001" failed with message: "UNAUTHORIZED: \"authentication required\"".
```

and the function doesn't seem to get created - I get `HTTP/1.1 404 Not Found` when trying to access it

The status for the square kservice:

```
status:
  conditions:
  - lastTransitionTime: 2018-10-29T16:02:28Z
    message: 'Revision "square-00001" failed with message: "UNAUTHORIZED: \"authentication
      required\"".'
    reason: RevisionFailed
    status: "False"
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T16:02:28Z
    message: Configuration "square" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: Ready
  - lastTransitionTime: 2018-10-29T16:02:28Z
    message: Configuration "square" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: RoutesReady
```

**Comment by trisberg** [comment]
It looks like there is an extra status reported after the build completes.

with `v21081029` release artifacts I see two status transitions

```
status:
  conditions:
  - lastTransitionTime: 2018-10-29T19:24:40Z
    status: Unknown
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T19:24:40Z
    message: Configuration "upper" is waiting for a Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: Ready
  - lastTransitionTime: 2018-10-29T19:24:40Z
    message: Configuration "upper" is waiting for a Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: RoutesReady

status:
  conditions:
  - lastTransitionTime: 2018-10-29T19:25:45Z
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T19:25:45Z
    status: "True"
    type: Ready
  - lastTransitionTime: 2018-10-29T19:25:45Z
    status: "True"
    type: RoutesReady
```

with `v21081009` release artifacts I see three status transitions

```
status:
  conditions:
  - lastTransitionTime: 2018-10-29T19:26:41Z
    status: Unknown
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T19:26:42Z
    message: Configuration "upper" is waiting for a Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: Ready
  - lastTransitionTime: 2018-10-29T19:26:41Z
    message: Configuration "upper" is waiting for a Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: RoutesReady

status:
  conditions:
  - lastTransitionTime: 2018-10-29T19:27:25Z
    message: 'Revision "upper-00001" failed with message: "The target is not receiving
      traffic.".'
    reason: RevisionFailed
    status: "False"
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T19:27:25Z
    message: Configuration "upper" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: Ready
  - lastTransitionTime: 2018-10-29T19:27:25Z
    message: Configuration "upper" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: RoutesReady

status:
  conditions:
  - lastTransitionTime: 2018-10-29T19:27:38Z
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: 2018-10-29T19:27:38Z
    status: "True"
    type: Ready
  - lastTransitionTime: 2018-10-29T19:27:38Z
    status: "True"
    type: RoutesReady
```
